services:
  example-application-backend:
    build:
      context: ${PWD}
      dockerfile: backend/Dockerfile
    restart: unless-stopped
    image: ${VEGITO_EXAMPLE_APPLICATION_BACKEND_IMAGE:-europe-west1-docker.pkg.dev/moov-dev-439608/docker-repository-public/vegito-example:application-backend-latest}
    env_file:
      - .env
    environment:
      LOCAL_WORKSPACE: ${PWD}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS:-${PWD}/infra/google-cloud-credentials.json}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID:-${GOOGLE_CLOUD_PROJECT_ID}}
      GCLOUD_PROJECT_ID: ${GCLOUD_PROJECT_ID:-${GOOGLE_CLOUD_PROJECT_ID}}
      VEGETABLE_IMAGES_BACKEND_PUBSUB_SUBSCRIPTION: ${LOCAL_FIREBASE_EMULATORS_PUBSUB_VEGETABLE_IMAGES_VALIDATED_BACKEND_SUBSCRIPTION:-vegetable-images-validated-backend}
      UI_CONFIG_FIREBASE_SECRET_ID: ${UI_CONFIG_FIREBASE_SECRET_ID:-projects/${GOOGLE_CLOUD_PROJECT_ID}/secrets/firebase-config-web/versions/2}
      UI_CONFIG_GOOGLEMAPS_SECRET_ID: ${UI_CONFIG_GOOGLEMAPS_SECRET_ID:-projects/${GOOGLE_CLOUD_PROJECT_ID}/secrets/google-maps-api-key/versions/1}
      VEGETABLE_CREATED_IMAGES_MODERATOR_PUBSUB_TOPIC: ${LOCAL_FIREBASE_EMULATORS_PUBSUB_VEGETABLE_IMAGES_CREATED_TOPIC:-vegetable-images-created}
      VEGETABLE_VALIDATED_IMAGES_BACKEND_PUBSUB_SUBSCRIPTION: ${LOCAL_FIREBASE_EMULATORS_PUBSUB_VEGETABLE_IMAGES_VALIDATED_BACKEND_SUBSCRIPTION:-vegetable-images-validated-backend}
      VEGETABLE_VALIDATED_IMAGES_CDN_PREFIX_URL: ${LOCAL_FIREBASE_EMULATORS_VEGETABLE_IMAGES_CDN_PREFIX_URL:-https://vegetable-images-cdn-prefix-url}
      VAULT_ADDR: http://vault-dev:8200
      VAULT_TOKEN: root
    volumes:
      - ${PWD}:${PWD}:cached
    networks:
      dev:
        aliases:
          - example-application-backend

  example-application-mobile:
    cap_add:
      - SYS_ADMIN
    image: ${VEGITO_EXAMPLE_APPLICATION_MOBILE_IMAGE:-${VEGITO_PUBLIC_REPOSITORY}/vegito-example:application-mobile-latest}
    env_file:
      - .env
    environment:
      LOCAL_ANDROID_EMULATOR_DATA: ${LOCAL_ANDROID_EMULATOR_DATA:-${PWD}/tests/mobile_images}
    privileged: true
    volumes:
      - ${LOCAL_WORKSPACE:-${PWD}}:${PWD}:cached
      - /var/run/dbus/system_bus_socket:/run/dbus/system_bus_socket
    group_add:
      - render
      - kvm
    devices:
      - /dev/kvm
    networks:
      dev:
        aliases:
          - example-application-mobile
    working_dir: ${PWD}/mobile

  example-application-tests:
    image: ${LOCAL_APPLICATION_TESTS_IMAGE:-${VEGITO_PUBLIC_REPOSITORY}/vegito-example:application-tests-latest}
    environment:
      VEGITO_BACKEND_URL_DEBUG: ${VEGITO_BACKEND_URL_DEBUG:-http://example-application-backend:8080}
      LOCAL_WORKSPACE: ${PWD}
      LOCAL_APPLICATION_TESTS_DIR: ${VEGITO_APPLICATION_TESTS_DIR:-${PWD}/vegito/tests}
      STORAGE_EMULATOR_HOST: ${VEGITO_STORAGE_EMULATOR_HOST:-http://firebase-emulators:9199}
      VEGITO_TESTS_DIR: ${VEGITO_TESTS_DIR:-${PWD}/tests}
    env_file:
      - .env
    volumes:
      - ${LOCAL_WORKSPACE:-${PWD}}:${PWD}:cached
    working_dir: ${PWD}
    command: |
      bash -c '
      set -eu
      sleep infinity
      '
